[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/api/delete-asset"
  to = "/.netlify/functions/delete-asset"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
